### ISSUE TITLE
Using multipart-payload makes the request hang.

### ISSUE THREAD

**Issue by eko234** [Bogdanp/racket-http-easy#11]
I'm trying to make a post request with some data, heres my code
``` racket
(define [send! config]
  (with-handlers ([exn? (λ (e) #f)])
    (match config
           [(hash-table
             {'dbpath dbpath}
             {'dbname dbname}
             {'tag    tag}
             ('key    key))
            (send-succeeded?
             (post "http://127.0.0.1:8086/send"
                   #:data (multipart-payload
                           (field-part "data" (jsexpr->string
                                               `#hasheq{(dbname . ,dbname)
                                                        (tag    . ,tag)
                                                        (key    . ,key)}))
                           (file-part  "file" (open-input-file (~a dbpath "/" dbname tag ".FBK.gz"))))))])))
```
`send-succeed?` just returns #t to anything btw, the thing is that this hangs for like a minute, but if i abort the program the opperation on the api just works if i allow it to hang just enough for it to actually send the request, the moment i kill the program, the api immediately processes the request, am I doing something wrong?, i suppose that `open-input-file ` should work just like the examples in which you use `open-input-string`. thanks in advance, hope you can help me out.

**Comment by Bogdanp** [comment]
This program produces the expected result for me:

```racket
#lang racket/base

(require json
         net/http-easy)

(response-json
 (post "https://httpbin.org/anything"
       #:data (multipart-payload
               (field-part "data" (jsexpr->string
                                   `#hasheq{(dbname . "test")
                                            (tag    . "tag")
                                            (key    . "key")}))
               (file-part  "file" (open-input-file "test.rkt"))))) ;; test.rkt refers to the program itself
```

Is it possible your server is the one stalling?

**Comment by eko234** [comment]
Really weird, I was testing with postman, and it works well that way, but when i try to do the same thing from racket, it just freezes. But, when i test both the client and the backend running in the same machine things work well, but now that the backend is in a production environment it just freezes,

**Comment by Bogdanp** [comment]
Do you have a reverse proxy in front of the server in production? Could that have some sort of file size limit that you're hitting? It's possible http easy doesn't deal well with uploads that are interrupted in the middle (e.g. because the upstream decided to close the connection because of the file size).

**Comment by eko234** [comment]
even with 1kb uploads it hangs, and the limit I have set is 100Mbs.

**Comment by eko234** [comment]
can i give you a test api key for you to try send a request?

**Comment by Bogdanp** [comment]
Yup! Feel free to e-mail it to me at bogdan@defn.io if you don't want to post it here.

**Comment by eko234** [comment]
I'll post it here, please try the following code.

**Comment by eko234** [comment]
#lang racket/base
(require json
         net/http-easy)

(response-json
 (post "http://backup.zendevp.com/send"
       #:data (multipart-payload
               (field-part "data" (jsexpr->string
                                   `#hasheq{(dbname . "DBSIPRED_INZA_MAESTRA_FB3-copia") ;; please try with this data
                                            (tag    . "tag")
                                            (key    . "shamowne")})) ;; this is the key
               (file-part  "file" (open-input-file "test.rkt"))))) ;; test.rkt refers to the program itself

**Comment by eko234** [comment]
It seems to be working, the files are arriving, but do you get a json response saying so?

**Comment by Bogdanp** [comment]
No, the request gets sent, but the server never responds. Here's a minimal example:

```racket
#lang racket/base

(require json
         net/http-easy
         racket/port
         racket/tcp)

(define-values (headers data)
  ((multipart-payload
     (field-part "data" (jsexpr->string
                         `#hasheq{(dbname . "DBSIPRED_INZA_MAESTRA_FB3-copia") ;; please try with this data
                                  (tag    . "tag")
                                  (key    . "shamowne")})) ;; this is the key
     (file-part  "file" (open-input-file "test.rkt")))
   (hasheq)))

(define-values (in out)
  (tcp-connect "backup.zendevp.com" 80))

(fprintf out "POST /send HTTP/1.1\r\n")
(fprintf out "Host: backup.zendevp.com\r\n")
(fprintf out "Content-type: ~s\r\n" (hash-ref headers 'content-type))
(fprintf out "\r\n")
(copy-port data out)
(close-output-port out)
(displayln "data sent")

(port->bytes in)
```

After a while, nginx replied with 

```
HTTP/1.1 504 Gateway Time-out
```

so it never received a reply from your server it looks like.

**Comment by eko234** [comment]
I see, I still don't understand why using postman works as intended...

**Comment by Bogdanp** [comment]
Is your server implemented in Racket? Can you share what the request handler looks like?

**Comment by eko234** [comment]
yes it is. 

``` racket
(define [send req]
  (with-handlers 
    ([exn? (λ (e)
             (response/jsexpr #hasheq{(result . "ERR")}))])
    (let ([filep (~>> req
                      (request-bindings/raw)
                      (bindings-assq #"file")
                      (binding:file/port-in))]
          [data (and~>> req
                        (request-bindings/raw)
                        (bindings-assq #"data")
                        (binding:form-value)
                        (bytes->string/utf-8)
                        (string->jsexpr))])
      (match data
        [(hash-table
          {'dbname dbname}
          {'tag    tag})
         (match (d:db-exists? dbname)
           [#t
            (u:port->file (~a s:cur-dir "/backups/" dbname tag "_" (current-inexact-milliseconds) ".FBK.gz") filep)
            (d:update-last-backup! dbname (date->iso8601 (today)))
            (response/jsexpr #hasheq{(result . "OK")
                                     (message . "file uploaded")})]
           [#f 
            (response/jsexpr #hasheq{(result . "ERR")
                                     (message . "dbname not registered")})])]
        [_ (response/jsexpr #hasheq{(result . "ERR")
                                    (message . "invalid request format")})]))))
```

**Comment by eko234** [comment]
the function `port->file` basically is a wrapper for `copy-port`

**Comment by Bogdanp** [comment]
My minimal example turned out to be wrong and that sent me down a wrong debugging hole, but the changes in d915c81 should fix this problem.

**Comment by eko234** [comment]
Thanks fren :)
