### ISSUE TITLE
Blocks on 204 No Content response

### ISSUE THREAD

**Issue by samdphillips** [Bogdanp/racket-http-easy#15]
The Spotify API has several requests that return 204 on success.  Unfortunately http-easy blocks waiting for content.  The response also doesn't have a content-length header.

Here is [one such request](https://developer.spotify.com/documentation/web-api/reference/#/operations/start-a-users-playback), and this is a trace (via curl) of the conversation:

```
> PUT /v1/me/player/play HTTP/1.1
> Host: api.spotify.com
> User-Agent: curl/7.74.0
> Accept: */*
> Authorization: Bearer SECRET_SECRET_SECRET
> Content-Type: application/json
> Content-Length: 116
> 
< HTTP/1.1 204 No Content
< cache-control: private, max-age=0
< x-robots-tag: noindex, nofollow
< access-control-allow-origin: *
< access-control-allow-headers: Accept, App-Platform, Authorization, Content-Type, Origin, Retry-After, Spotify-App-Version, X-Cloud-Trace-Context, client-token, content-access-token
< access-control-allow-methods: GET, POST, OPTIONS, PUT, DELETE, PATCH
< access-control-allow-credentials: true
< access-control-max-age: 604800
< strict-transport-security: max-age=31536000
< x-content-type-options: nosniff
< vary: Accept-Encoding
< date: Mon, 06 Dec 2021 05:52:10 GMT
< server: envoy
< Via: HTTP/2 edgeproxy, 1.1 google
< Alt-Svc: clear
< 
```

**Comment by samdphillips** [comment]
I have found a workaround by manually handling the response output.  Without `#:stream? #t` on the `put` call it would hang there.

```racket
(define resp
   (put url
        #:stream? #t
        #:auth auth-proc))        
(close-input-port (response-output resp))
(response-close! resp)
```

**Comment by Bogdanp** [comment]
Can you reproduce the issue against this server?

```racket
#lang racket/base

(require web-server/http
         web-server/servlet-dispatch
         web-server/web-server)

(define stop
  (serve
   #:port 9999
   #:dispatch (dispatch/servlet
               (lambda (_req)
                 (response/output
                  #:code 204
                  void)))))

(with-handlers ([exn:break? (λ (_e) (stop))])
  (sync never-evt))
```

I can't, so maybe something else is going on (or maybe I'm doing a bad job of reproducing the Spotify response, which I haven't tried yet because getting an auth token looks like a bit of a pain).

**Comment by samdphillips** [comment]
I haven't had a chance to try out that server yet.  Something that occurs to me is perhaps the Spotify connection is still left open after the response header for pipelining and the Racket server closes the connection after the response is completed?

**Comment by Bogdanp** [comment]
Whoops, hadn't noticed this got closed yesterday. This was fixed upstream so it should work fine after the next release of Racket.
