### ISSUE TITLE
Supporting for sending request through custom ports?

### ISSUE THREAD

**Issue by yjqww6** [Bogdanp/racket-http-easy#2]
net/http-client supports sending request through custom ports via #:ssl?, since it accepts base-ssl?-tnl/c. For example, unix-socket request could be accomplished like 
```
#lang racket
(require racket/port net/http-client)
(require racket/unix-socket)
(define-values (i o) (unix-socket-connect "/var/run/docker.sock"))
(define hc (http-conn-open "" #:ssl? (list #f i o close-output-port)))
(define-values (status header port)
  (http-conn-sendrecv! hc "/images/json"))
(displayln (port->bytes port))
(http-conn-close! hc)
```

But in http-easy, I found it only accepts ssl-client-context? in make-session. 
Are there any plans for supporting similar things?

**Comment by Bogdanp** [comment]
Thanks for the example! That's a use case I hadn't really considered beyond thinking about proxying in general. I'll make sure to keep this in mind when I start working on proxy support.

**Comment by Bogdanp** [comment]
Hey @yjqww6, I forgot to ask, but do the changes in https://github.com/Bogdanp/racket-http-easy/pull/10 work for your use cases? The `http+unix` scheme should work as a shorthand for making requests to a UNIX socket and proxies can be used to make arbitrary connections like in your example.

**Comment by yjqww6** [comment]
It seems good enough for my use cases. Thanks for you work!
