### ISSUE TITLE
recovering from timeouts when retrieving URLs

### ISSUE THREAD

**Issue by alex-hhh** [Bogdanp/racket-http-easy#21]
Hi Bogdan,

I suppose this is more of a support request for using this package -- in particular for handling timeouts...

## Some Background Information

My `map-widget` package uses `get` to retrieve network tiles which are cached locally.  Occasionally (happened twice), when I had poor network connectivity, requests started timing out.  While the `map-widget` attempts to handle such errors, it ended up with a corrupt cached local copy of the tiles, that is the wrong tile was stored with the wrong URL, as if the actual response came in later and was supplied to another `get` request (I am not sure if this is the case).

Currently the overall architecture is

* There is a list of map tiles to be downloaded that is managed by the package
* There are three racket threads, each retrieving from this list and using `http-easy`'s `get` function to retrieve the PNG image associated with the tile (there code handles multi-threaded access to the shared tile list correctly, it all works fine when there are no timeouts)
* When an exception occurs, the tile is placed again into the list to be tried later.

## The Question

The tile download code does not create a separate session for downloading, it relies on the default `current-session` from the package, also it does nothing when an exception occurs from the `get` call and continues to issue new requests.   

The actual code that uses the `get` call is below:

https://github.com/alex-hhh/map-widget/blob/2eb8e2c0f44192c09dc924888c4fd3deb1d05e22/private/map-tiles.rkt#L426 

Should a separate session be created for each download thread and also, is there some recovery that needs to be done when an exception occurs?

Thanks,
Alex.

**Comment by Bogdanp** [comment]
Thanks for the report! This was a definite bug in how timeouts were being handled and should be fixed as of the last commit. Please give it a try and let me know if you run into any other issues.

Re. sessions: they are thread-safe so it should be completely fine to use a single session for all your requests. Any recovery should be handled by the library, so you shouldn't have to worry about doing anything special when exceptions occur.

**Comment by alex-hhh** [comment]
Thanks for identifying and fixing the problem so quickly, I'll update to the latest `http-easy` version.
