### ISSUE TITLE
Location after a redirect

### ISSUE THREAD

**Issue by octplane** [Bogdanp/racket-http-easy#22]
Hello!

I'm crawling a page that sends a redirect and after that, I want to submit a form and the `action` of the form is a relative url. I was wondering if there is a way to get the `location`/`hostname` of the current `response`. I could probably inspect the `response-history` but there could be a trick I missed in the source code.

Thanks for your time and this nice lib! 💌 
Oct.

**Comment by Bogdanp** [comment]
Hi @octplane! Using `response-history` here is the way to go.  You should be able to do something along the lines of:

```racket
(~> (car (response-history res))
    (response-headers-ref 'location)
    (bytes->string/utf-8)
    (string->url))
```

If the response history of a response is non-null, every entry in the list is guaranteed to have a `Location` header, and the entries are in reverse order, so the head of the list represents the most recent redirect.

Let me know if you run into any issues.

**Comment by octplane** [comment]
It works as expected, thanks!
