### ISSUE TITLE
No referer in sight?

### ISSUE THREAD

**Issue by octplane** [Bogdanp/racket-http-easy#23]
Hello again,

I'm trying to, ahem, scrape, some data on the internet and particularly to port a working Scrapy implementation to Racket, because why not. It seems however that I can't replicate the results I have in Scrapy because the `Referer` header is not populated in the http-easy implementation (I'm not sure this is because of that, but my current hobby is running both implementations through `Proxyman` and diffing the data with my eyes). 

I'm not sure how much this is part of some spec but because your client follows Redirect, this is something that I half-expected to be there, but 🤷🏻 ...

**Comment by Bogdanp** [comment]
I think the relevant spec is [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html#name-referer). I don't think it's common for HTTP clients to populate the referer since they don't act like the typical user agent, though I understand why Scrapy would because it's more of a framework than a simple client.

Would it help if you could access the request URL of a response in the `response-history` list?

**Comment by octplane** [comment]
I think I could disable the auto-redirect follow feature and craft this header entirely by myself, couldn't I?

**Comment by Bogdanp** [comment]
Yep, that would also work.

**Comment by octplane** [comment]
Thanks for the hint. It worked well until I found something that's not behaving the way I wanted in `(alist->form-urlencoded)`, so much deeper in the code. Not sure I can work around that and keep using your lib...

**Comment by Bogdanp** [comment]
Can you say more about what the problem there is? I'm not sure I follow.

**Comment by octplane** [comment]
I'm sending a request to `https://remotehost.com?login=http://anotherhost.com` and you lib naturally converts the `login` parameter value to an url-encoded value which should be reasonnable except `remotehost` does not decode values and generates an invalid response.

I spent some time debugging that because I failed to see the `%3A%2F%2F` in the url http-easy was building (at least, it told me how to wire a mitm proxy into Racket). I think it would be better if I built the request entirely myself to prevent any form of escaping...
