### ISSUE TITLE
I wrote a SOCKS5 proxy library that integrates with http-easy

### ISSUE THREAD

**Issue by cloudrac3r** [Bogdanp/racket-http-easy#24]
Just thought you'd be interested to know that somebody else implemented your proxy interface!

Docs: https://docs.racket-lang.org/socks5/Provides.html#%28def._%28%28lib._socks5%2Fmain..rkt%29._make-socks5-proxy%29%29
Woven source: https://docs.racket-lang.org/socks5/Proxy_for_http-easy.html 
Show & Tell: https://racket.discourse.group/t/socks5-my-new-package-written-with-literate-programming/1727
Raw source: https://github.com/cloudrac3r/racket-socks5 

If you want, you can mention it in your documentation. No pressure though :)

You don't need to do anything on this issue, I'm just letting you know about my library.

Feedback welcome!

**Comment by Bogdanp** [comment]
Looks great! Thanks for the heads-up. I've added a link to the docs.
