### ISSUE TITLE
%2A is force decoded to *

### ISSUE THREAD

**Issue by cloudrac3r** [Bogdanp/racket-http-easy#25]
A particularly picky website requires me to send a GET request with `%2A`, however the http-easy internals force this to be decoded to `*` via the [`(->url urlish)` and `(url-path&query u params*)` round-trip](https://github.com/Bogdanp/racket-http-easy/blob/master/http-easy-lib/http-easy/private/session.rkt). The website does not accept `*` and sends a 301 redirect with `*` replaced with `%2A`. This means http-easy and the website are now in an infinite loop where http-easy changes to `*` and the website asks to change it back to `%2A`. It only leaves the loop due to #:max-redirects.

I think that if no #:params are required then http-easy should keep the provided URL without doing the round-trip conversion, to make sure each byte stays exactly the same as provided.

Since this is such an edge-case, if it is difficult for you to implement then I would be happy with suggestions for a workaround. I tried looking through your code to see if I could come up with a PR, but I figured you would know your own utility functions better than I do.

**Comment by Bogdanp** [comment]
Does it work if you encode the `%`? Eg. `example.com?param=%252A`?

**Comment by cloudrac3r** [comment]
Yeah, that actually does work, haha! I will see if I can write this workaround into my code

**Comment by Bogdanp** [comment]
Digging in a little bit, this appears to be a bug in `net/uri-codec` (unless I'm missing something): 

```racket
> (require net/uri-codec)
> (alist->form-urlencoded '((param . "*")))
"param=*"
> (alist->form-urlencoded '((param . "%")))
"param=%25"
```

RFC3986 states that `*` is a reserved char so it should be encoded.

**Comment by cloudrac3r** [comment]
\* is not in the x-www-form-urlencoded set, so it doesn't need to be encoded in query strings according to the spec. Of course, server behaviour may differ.  https://url.spec.whatwg.org/#application-x-www-form-urlencoded-percent-encode-set

**Comment by Bogdanp** [comment]
Yes, you're right. I was confused because I was comparing `alist->form-urlencoded` to Python's `urlencode`, which does encode `*`. Re. the overall issue, probably it would be better not to round-trip redirect URLs, as you suggest, but that seems like it'll be a bit painful. I'll look into it more later this week.

**Comment by cloudrac3r** [comment]
If I can get %252A working in my real code, there's probably no need for you to work on this - this is such an edge case of an edge case!

**Comment by cloudrac3r** [comment]
A related issue is that %20 is also force-decoded to + when it appears after ? in the URL (i.e. it is part of the query parameters). While the URL spec says you're _supposed_ to encode with +, there's a shocking number of websites out there that rely on %20 instead.

The %2520 trick doesn't work in this case, because it remains at %2520. I cannot find a workaround that would allow me to send %20 directly.

**Comment by Bogdanp** [comment]
Hi @cloudrac3r, I know it's been a while, so no worries if you don't feel like testing this out, but #29 provides a solution to your last comment. Would you be willing to give it a try? Something along the lines of `(get (string->url/literal "https://example.com?foo=a%20b"))` would let you pass the value of `foo` literally to the server as `a%20b` without any {de,en}coding.
