### ISSUE TITLE
Comparing responses from `http-easy` and `curl`

### ISSUE THREAD

**Issue by evdubs** [Bogdanp/racket-http-easy#28]
Hi,

I am trying to retrieve a cookie set after logging in. I can do this with `curl`:

```bash
$ curl --data "email=email&password=password&remember=true" https://service/login_submit.ashx
```

With this, I get back a `.ASPXAUTH` cookie that I can then use.

However, with `http-easy`, when I try things like the following:

```racket
(require net/http-easy)

(post "https://service/login_submit.ashx"
      #:data "email=email&password=password&remember=true"
      #:headers (hash 'Content-Type "application/x-www-form-urlencoded"))

(post "https://service/login_submit.ashx"
      #:form '((email . "email")
               (password . "password")
               (remember . "true")))
```

I do not get back the expected `.ASPXAUTH` cookie. How can I go about debugging this to see what is being sent by `http-easy` so that I can try to determine why I am not getting the cookie I expect?

**Comment by evdubs** [comment]
For what it's worth, I am using `response-headers` to view the headers.

**Comment by evdubs** [comment]
Further, the following also works for me:

```racket
(require net/http-client)

(define-values (status headers body)
  (http-sendrecv "service"
                 "/login_submit.ashx"
                 #:ssl? #t
                 #:method "POST"
                 #:headers (list "Content-Type: application/x-www-form-urlencoded")
                 #:data "email=email&password=password&remember=true"))
```

**Comment by Bogdanp** [comment]
On a cursory look, I'm not sure what it could be. Is there any way I can have access to the service to debug this (email in profile)?

**Comment by Bogdanp** [comment]
@evdubs thanks for sending me the service over email. I don't think there is an issue here after all, though I see how it can be confusing. What's happening is the service redirects on successful login and http-easy follows the redirect. So, you can either write

```racket
(post "https://service/login_submit.ashx"
      #:max-redirects 0
      #:form '((email . "email")
               (password . "password")))
```

To disable the redirect-following behavior or get the response history via `response-history`. You could also set up your session with a cookie jar and that way the cookies will be preserved across requests and you won't have to inspect the history:

```racket
#lang racket/base

(require net/cookies
         net/http-easy
         net/url
         racket/class)

(define cookies (new list-cookie-jar%))
(current-session
 (make-session
  #:cookie-jar cookies))
(define res
  (post "https://service/login_submit.ashx"
        #:max-redirects 0
        #:form `((email . "username")
                 (password . "password"))))
(send cookies cookies-matching (string->url "https://service"))
```

**Comment by evdubs** [comment]
Confirmed! `#:max-redirects 0` allows me to retrieve the cookie I expect. Thanks.
