### ISSUE TITLE
Slower than CURL?

### ISSUE THREAD

**Issue by srfoster** [Bogdanp/racket-http-easy#6]
Not sure if it's just me, but when I do a `(post SOME-LOCAL-URL #:data ...)`, it takes over a second for the request to arrive at `SOME-LOCAL-URL`.  Doing a `(system "curl -X POST SOME-LOCAL-URL")` is much faster.

Note: This seems to affect  `simple-http` as well as basically all the Racket HTTP libraries I've tried. 

I posted about this on the Racket mailing list a while back, and again this morning: 

https://groups.google.com/u/1/g/racket-users/c/rkOv0BuA3Uw/m/lc_7N8P_AwAJ

**Comment by Bogdanp** [comment]
@srfoster it would be helpful to know what `SOME-LOCAL-URL` looks like to be able to narrow things down. In addition to that, it would be helpful to know what version of Racket you're running. When I run an HTTP server using Python (`python3 -m http.server`) and then execute the following code

```racket
(time (get "127.0.0.1:8000"))
```

I get

```
cpu time: 1 real time: 1 gc time: 0
```

Same deal if I make a POST request. 

Any chance it's DNS resolution that's taking so long? Is the server you're connecting to behind SSL?

**Comment by Bogdanp** [comment]
I just watched the video in the OP. What happens if you pass `#:close? #t` to `post`?

If that is also slow, I'd try something like this:

```racket
#lang racket/base

(require net/uri-codec
         racket/port
         racket/tcp)

(define-values (in out)
  (tcp-connect "127.0.0.1" 8000))

(define data
  (string->bytes/utf-8
   (alist->form-urlencoded '((x . "1")
                             (y . "2")))))

(parameterize ([current-output-port out])
  (write-bytes #"POST /\r\n")
  (write-bytes #"Connection: close\r\n")
  (write-bytes #"Content-Type: application/x-www-form-urlencoded\r\n")
  (write-bytes #"Content-Length: ")
  (write-bytes (string->bytes/utf-8 (number->string (bytes-length data))))
  (write-bytes #"\r\n\r\n")
  (write-bytes data))

(tcp-abandon-port out)
(port->bytes in)
(close-input-port in)
```

to rule out any issues with this library or `net/http-client`.

**Comment by srfoster** [comment]
Interesting, here's some server code:

```
#lang racket
(require web-server/servlet
         web-server/servlet-env)
 
(define (my-app req)
  (displayln "Got it")
  (response/xexpr
   `(html (head (title "Hello world!"))
          (body (p "Hey out there!")))))
 
(serve/servlet my-app
               #:port 8000
               #:servlet-regexp #rx"")
```

Here's my client code:

```
#lang racket

(require net/http-easy)

(displayln "Starting Test 1")
(time
 (get "127.0.0.1:8000"))
(displayln "Ending Test")

(displayln "Starting Test 2")
(time
 (get "localhost:8000"))
(displayln "Ending Test")

(displayln "Starting Test 3")
(time
 (get "http://localhost:8000"))
(displayln "Ending Test")
```

And I'm definitely getting different behavior on `127.0.0.1` than on `localhost` (which is much slower).  

```
Starting Test 1
cpu time: 63 real time: 65 gc time: 32
#<response>
Ending Test
Starting Test 2
cpu time: 312 real time: 2022 gc time: 46
#<response>
Ending Test
Starting Test 3
cpu time: 203 real time: 2017 gc time: 32
#<response>
Ending Test
```

In Chrome, requests to both `localhost` and `127.0.0.1` appear to be equally fast.  I guess I would expect `localhost` to be slower, but not by 2 seconds.  (Feel free to correct me if I'm wrong about that.)  This seems more like it might be an issue with my system than any Racket libraries, though.  Feel free to close this if you agree!!

And thanks for the help!  Solved my problem.  There's no place like `127.0.0.1` :)

**Comment by Bogdanp** [comment]
Sounds like a DNS resolution issue in that case. There shouldn't nearly be that much of a difference between using the IP address and the hostname, and indeed, there isn't one on my machine. Chrome has a local DNS cache, so you'd only notice the slowdown of `localhost` VS `127.0.0.1` on the first request. I'm not sure about curl, but it may also be doing something clever.

I'd check to make sure you have an entry like

```
127.0.0.1       localhost
```

in your `/etc/hosts` file and that you're not running a (potentially-misconfigured) custom DNS resolver (like `dnsmasq`). You can run `dig +all localhost` to see how that hostname is being resolved (and by whom -- the `;; SERVER: ` line).  Finally, on macOS, you can list the DNS resolvers by issuing a `scutil --dns` command so that might help you find if you have a bad resolver in there.
